def player_stats(name):
    player_info= {
        "Darius Garland":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "Nike",
        },
        "Joshua Zirzke":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "Addidas",
        },
        "Daglus Luiz":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "New Balance",
        },
        
        "Fernades":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "Nike",
        },
        "Ronaldo":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "Addidas",
        },
        "D Maria":{
        "name": "Darius Garland",
        "number": 10,
        "position": "Point Guard",
        "points_per_game": 21.7,
        "rebounds_per_game": 3.3,
        "assists_per_game": 8.6,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.1,
        "career_points": 3142,
        "age": 22,
        "height_inches": 73,
        "shoe_brand": "New Balance",
        }
    }
        {"Nike"=[]}
        { "Addidas"=[]}
        {"New Balance"=[]}
    print (player_info.get(name, "Player Not Found"))
player_stats("Darius Garlan")

